-- AlterTable
ALTER TABLE "PropertyPlan" ADD COLUMN     "builtUpArea" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "coverage" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "floors" INTEGER DEFAULT 1,
ADD COLUMN     "frontSetback" DOUBLE PRECISION DEFAULT 6.0,
ADD COLUMN     "fsiUsed" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "parentPlanId" TEXT,
ADD COLUMN     "parkingSpaces" INTEGER DEFAULT 0,
ADD COLUMN     "rearSetback" DOUBLE PRECISION DEFAULT 3.0,
ADD COLUMN     "requestedFloors" INTEGER DEFAULT 1,
ADD COLUMN     "sideSetbacks" DOUBLE PRECISION DEFAULT 3.0,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'DRAFT',
ADD COLUMN     "totalUnits" INTEGER DEFAULT 0,
ADD COLUMN     "version" TEXT NOT NULL DEFAULT 'V1';
